//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CinemaWeb_DNP1.CardValidator {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CreditCardValidatorSoap", Namespace="http://localhost/SmartPayments/")]
    public partial class CreditCardValidator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetCardTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCommercialCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidCardLengthOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidExpDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidMod10OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNetworkIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsFSACardOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsValidCheckRoutingNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsDebitCardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CreditCardValidator() {
            this.Url = global::CinemaWeb_DNP1.Properties.Settings.Default.CinemaWeb_DNP1_CardValidator_CreditCardValidator;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetCardTypeCompletedEventHandler GetCardTypeCompleted;
        
        /// <remarks/>
        public event IsCommercialCardCompletedEventHandler IsCommercialCardCompleted;
        
        /// <remarks/>
        public event ValidCardCompletedEventHandler ValidCardCompleted;
        
        /// <remarks/>
        public event ValidCardLengthCompletedEventHandler ValidCardLengthCompleted;
        
        /// <remarks/>
        public event ValidExpDateCompletedEventHandler ValidExpDateCompleted;
        
        /// <remarks/>
        public event ValidMod10CompletedEventHandler ValidMod10Completed;
        
        /// <remarks/>
        public event GetNetworkIDCompletedEventHandler GetNetworkIDCompleted;
        
        /// <remarks/>
        public event IsFSACardCompletedEventHandler IsFSACardCompleted;
        
        /// <remarks/>
        public event IsValidCheckRoutingNumberCompletedEventHandler IsValidCheckRoutingNumberCompleted;
        
        /// <remarks/>
        public event IsDebitCardCompletedEventHandler IsDebitCardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/GetCardType", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCardType(string CardNumber) {
            object[] results = this.Invoke("GetCardType", new object[] {
                        CardNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardTypeAsync(string CardNumber) {
            this.GetCardTypeAsync(CardNumber, null);
        }
        
        /// <remarks/>
        public void GetCardTypeAsync(string CardNumber, object userState) {
            if ((this.GetCardTypeOperationCompleted == null)) {
                this.GetCardTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardTypeOperationCompleted);
            }
            this.InvokeAsync("GetCardType", new object[] {
                        CardNumber}, this.GetCardTypeOperationCompleted, userState);
        }
        
        private void OnGetCardTypeOperationCompleted(object arg) {
            if ((this.GetCardTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardTypeCompleted(this, new GetCardTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/IsCommercialCard", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsCommercialCard(string CardNumber) {
            object[] results = this.Invoke("IsCommercialCard", new object[] {
                        CardNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsCommercialCardAsync(string CardNumber) {
            this.IsCommercialCardAsync(CardNumber, null);
        }
        
        /// <remarks/>
        public void IsCommercialCardAsync(string CardNumber, object userState) {
            if ((this.IsCommercialCardOperationCompleted == null)) {
                this.IsCommercialCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCommercialCardOperationCompleted);
            }
            this.InvokeAsync("IsCommercialCard", new object[] {
                        CardNumber}, this.IsCommercialCardOperationCompleted, userState);
        }
        
        private void OnIsCommercialCardOperationCompleted(object arg) {
            if ((this.IsCommercialCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCommercialCardCompleted(this, new IsCommercialCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/ValidCard", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ValidCard(string CardNumber, string ExpDate) {
            object[] results = this.Invoke("ValidCard", new object[] {
                        CardNumber,
                        ExpDate});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ValidCardAsync(string CardNumber, string ExpDate) {
            this.ValidCardAsync(CardNumber, ExpDate, null);
        }
        
        /// <remarks/>
        public void ValidCardAsync(string CardNumber, string ExpDate, object userState) {
            if ((this.ValidCardOperationCompleted == null)) {
                this.ValidCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidCardOperationCompleted);
            }
            this.InvokeAsync("ValidCard", new object[] {
                        CardNumber,
                        ExpDate}, this.ValidCardOperationCompleted, userState);
        }
        
        private void OnValidCardOperationCompleted(object arg) {
            if ((this.ValidCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidCardCompleted(this, new ValidCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/ValidCardLength", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidCardLength(string CardNumber) {
            object[] results = this.Invoke("ValidCardLength", new object[] {
                        CardNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidCardLengthAsync(string CardNumber) {
            this.ValidCardLengthAsync(CardNumber, null);
        }
        
        /// <remarks/>
        public void ValidCardLengthAsync(string CardNumber, object userState) {
            if ((this.ValidCardLengthOperationCompleted == null)) {
                this.ValidCardLengthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidCardLengthOperationCompleted);
            }
            this.InvokeAsync("ValidCardLength", new object[] {
                        CardNumber}, this.ValidCardLengthOperationCompleted, userState);
        }
        
        private void OnValidCardLengthOperationCompleted(object arg) {
            if ((this.ValidCardLengthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidCardLengthCompleted(this, new ValidCardLengthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/ValidExpDate", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidExpDate(string ExpDate) {
            object[] results = this.Invoke("ValidExpDate", new object[] {
                        ExpDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidExpDateAsync(string ExpDate) {
            this.ValidExpDateAsync(ExpDate, null);
        }
        
        /// <remarks/>
        public void ValidExpDateAsync(string ExpDate, object userState) {
            if ((this.ValidExpDateOperationCompleted == null)) {
                this.ValidExpDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidExpDateOperationCompleted);
            }
            this.InvokeAsync("ValidExpDate", new object[] {
                        ExpDate}, this.ValidExpDateOperationCompleted, userState);
        }
        
        private void OnValidExpDateOperationCompleted(object arg) {
            if ((this.ValidExpDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidExpDateCompleted(this, new ValidExpDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/ValidMod10", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidMod10(string CardNumber) {
            object[] results = this.Invoke("ValidMod10", new object[] {
                        CardNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidMod10Async(string CardNumber) {
            this.ValidMod10Async(CardNumber, null);
        }
        
        /// <remarks/>
        public void ValidMod10Async(string CardNumber, object userState) {
            if ((this.ValidMod10OperationCompleted == null)) {
                this.ValidMod10OperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidMod10OperationCompleted);
            }
            this.InvokeAsync("ValidMod10", new object[] {
                        CardNumber}, this.ValidMod10OperationCompleted, userState);
        }
        
        private void OnValidMod10OperationCompleted(object arg) {
            if ((this.ValidMod10Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidMod10Completed(this, new ValidMod10CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/GetNetworkID", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response GetNetworkID(string UserName, string Password, string CardNumber) {
            object[] results = this.Invoke("GetNetworkID", new object[] {
                        UserName,
                        Password,
                        CardNumber});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void GetNetworkIDAsync(string UserName, string Password, string CardNumber) {
            this.GetNetworkIDAsync(UserName, Password, CardNumber, null);
        }
        
        /// <remarks/>
        public void GetNetworkIDAsync(string UserName, string Password, string CardNumber, object userState) {
            if ((this.GetNetworkIDOperationCompleted == null)) {
                this.GetNetworkIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNetworkIDOperationCompleted);
            }
            this.InvokeAsync("GetNetworkID", new object[] {
                        UserName,
                        Password,
                        CardNumber}, this.GetNetworkIDOperationCompleted, userState);
        }
        
        private void OnGetNetworkIDOperationCompleted(object arg) {
            if ((this.GetNetworkIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNetworkIDCompleted(this, new GetNetworkIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/IsFSACard", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsFSACard(string CardNumber, string PNRef, string Vendor, string CcInfoKey) {
            object[] results = this.Invoke("IsFSACard", new object[] {
                        CardNumber,
                        PNRef,
                        Vendor,
                        CcInfoKey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsFSACardAsync(string CardNumber, string PNRef, string Vendor, string CcInfoKey) {
            this.IsFSACardAsync(CardNumber, PNRef, Vendor, CcInfoKey, null);
        }
        
        /// <remarks/>
        public void IsFSACardAsync(string CardNumber, string PNRef, string Vendor, string CcInfoKey, object userState) {
            if ((this.IsFSACardOperationCompleted == null)) {
                this.IsFSACardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsFSACardOperationCompleted);
            }
            this.InvokeAsync("IsFSACard", new object[] {
                        CardNumber,
                        PNRef,
                        Vendor,
                        CcInfoKey}, this.IsFSACardOperationCompleted, userState);
        }
        
        private void OnIsFSACardOperationCompleted(object arg) {
            if ((this.IsFSACardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsFSACardCompleted(this, new IsFSACardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/IsValidCheckRoutingNumber", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsValidCheckRoutingNumber(string RoutingNumber) {
            object[] results = this.Invoke("IsValidCheckRoutingNumber", new object[] {
                        RoutingNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsValidCheckRoutingNumberAsync(string RoutingNumber) {
            this.IsValidCheckRoutingNumberAsync(RoutingNumber, null);
        }
        
        /// <remarks/>
        public void IsValidCheckRoutingNumberAsync(string RoutingNumber, object userState) {
            if ((this.IsValidCheckRoutingNumberOperationCompleted == null)) {
                this.IsValidCheckRoutingNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsValidCheckRoutingNumberOperationCompleted);
            }
            this.InvokeAsync("IsValidCheckRoutingNumber", new object[] {
                        RoutingNumber}, this.IsValidCheckRoutingNumberOperationCompleted, userState);
        }
        
        private void OnIsValidCheckRoutingNumberOperationCompleted(object arg) {
            if ((this.IsValidCheckRoutingNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsValidCheckRoutingNumberCompleted(this, new IsValidCheckRoutingNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/SmartPayments/IsDebitCard", RequestNamespace="http://localhost/SmartPayments/", ResponseNamespace="http://localhost/SmartPayments/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode IsDebitCard(string CardNumber) {
            object[] results = this.Invoke("IsDebitCard", new object[] {
                        CardNumber});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void IsDebitCardAsync(string CardNumber) {
            this.IsDebitCardAsync(CardNumber, null);
        }
        
        /// <remarks/>
        public void IsDebitCardAsync(string CardNumber, object userState) {
            if ((this.IsDebitCardOperationCompleted == null)) {
                this.IsDebitCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsDebitCardOperationCompleted);
            }
            this.InvokeAsync("IsDebitCard", new object[] {
                        CardNumber}, this.IsDebitCardOperationCompleted, userState);
        }
        
        private void OnIsDebitCardOperationCompleted(object arg) {
            if ((this.IsDebitCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsDebitCardCompleted(this, new IsDebitCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/SmartPayments/")]
    public partial class Response {
        
        private int resultField;
        
        private string respMSGField;
        
        private string messageField;
        
        private string message1Field;
        
        private string message2Field;
        
        private string authCodeField;
        
        private string pNRefField;
        
        private string hostCodeField;
        
        private string hostURLField;
        
        private string receiptURLField;
        
        private string getAVSResultField;
        
        private string getAVSResultTXTField;
        
        private string getStreetMatchTXTField;
        
        private string getZipMatchTXTField;
        
        private string getCVResultField;
        
        private string getCVResultTXTField;
        
        private string getGetOrigResultField;
        
        private string getCommercialCardField;
        
        private string workingKeyField;
        
        private string keyPointerField;
        
        private string extDataField;
        
        /// <remarks/>
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string RespMSG {
            get {
                return this.respMSGField;
            }
            set {
                this.respMSGField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Message1 {
            get {
                return this.message1Field;
            }
            set {
                this.message1Field = value;
            }
        }
        
        /// <remarks/>
        public string Message2 {
            get {
                return this.message2Field;
            }
            set {
                this.message2Field = value;
            }
        }
        
        /// <remarks/>
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PNRef {
            get {
                return this.pNRefField;
            }
            set {
                this.pNRefField = value;
            }
        }
        
        /// <remarks/>
        public string HostCode {
            get {
                return this.hostCodeField;
            }
            set {
                this.hostCodeField = value;
            }
        }
        
        /// <remarks/>
        public string HostURL {
            get {
                return this.hostURLField;
            }
            set {
                this.hostURLField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptURL {
            get {
                return this.receiptURLField;
            }
            set {
                this.receiptURLField = value;
            }
        }
        
        /// <remarks/>
        public string GetAVSResult {
            get {
                return this.getAVSResultField;
            }
            set {
                this.getAVSResultField = value;
            }
        }
        
        /// <remarks/>
        public string GetAVSResultTXT {
            get {
                return this.getAVSResultTXTField;
            }
            set {
                this.getAVSResultTXTField = value;
            }
        }
        
        /// <remarks/>
        public string GetStreetMatchTXT {
            get {
                return this.getStreetMatchTXTField;
            }
            set {
                this.getStreetMatchTXTField = value;
            }
        }
        
        /// <remarks/>
        public string GetZipMatchTXT {
            get {
                return this.getZipMatchTXTField;
            }
            set {
                this.getZipMatchTXTField = value;
            }
        }
        
        /// <remarks/>
        public string GetCVResult {
            get {
                return this.getCVResultField;
            }
            set {
                this.getCVResultField = value;
            }
        }
        
        /// <remarks/>
        public string GetCVResultTXT {
            get {
                return this.getCVResultTXTField;
            }
            set {
                this.getCVResultTXTField = value;
            }
        }
        
        /// <remarks/>
        public string GetGetOrigResult {
            get {
                return this.getGetOrigResultField;
            }
            set {
                this.getGetOrigResultField = value;
            }
        }
        
        /// <remarks/>
        public string GetCommercialCard {
            get {
                return this.getCommercialCardField;
            }
            set {
                this.getCommercialCardField = value;
            }
        }
        
        /// <remarks/>
        public string WorkingKey {
            get {
                return this.workingKeyField;
            }
            set {
                this.workingKeyField = value;
            }
        }
        
        /// <remarks/>
        public string KeyPointer {
            get {
                return this.keyPointerField;
            }
            set {
                this.keyPointerField = value;
            }
        }
        
        /// <remarks/>
        public string ExtData {
            get {
                return this.extDataField;
            }
            set {
                this.extDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetCardTypeCompletedEventHandler(object sender, GetCardTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IsCommercialCardCompletedEventHandler(object sender, IsCommercialCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCommercialCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCommercialCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ValidCardCompletedEventHandler(object sender, ValidCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ValidCardLengthCompletedEventHandler(object sender, ValidCardLengthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidCardLengthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidCardLengthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ValidExpDateCompletedEventHandler(object sender, ValidExpDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidExpDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidExpDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ValidMod10CompletedEventHandler(object sender, ValidMod10CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidMod10CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidMod10CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetNetworkIDCompletedEventHandler(object sender, GetNetworkIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNetworkIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNetworkIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IsFSACardCompletedEventHandler(object sender, IsFSACardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsFSACardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsFSACardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IsValidCheckRoutingNumberCompletedEventHandler(object sender, IsValidCheckRoutingNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsValidCheckRoutingNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsValidCheckRoutingNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void IsDebitCardCompletedEventHandler(object sender, IsDebitCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsDebitCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsDebitCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591